export enum PermissionEnum {
  CREATE_USER = 'create_user',
  VIEW_USERS = 'view_users',
  VIEW_USER = 'view_user',
  UPDATE_USER = 'update_user',
  DELETE_USER = 'delete_user',
  CREATE_ROLE = 'create_role',
  VIEW_ROLES = 'view_roles',
  VIEW_ROLE = 'view_role',
  UPDATE_ROLE = 'update_role',
  DELETE_ROLE = 'delete_role',
  ASSIGN_ROLE = 'assign_role',
  CREATE_PERMISSION = 'create_permission',
  VIEW_PERMISSIONS = 'view_permissions',
  VIEW_PERMISSION = 'view_permission',
  UPDATE_PERMISSION = 'update_permission',
  DELETE_PERMISSION = 'delete_permission',
  ASSIGN_PERMISSION = 'assign_permission',
}
